//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampRcon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampRcon.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to connect to the server failed..
        /// </summary>
        public static string AddServerErrorValue {
            get {
                return ResourceManager.GetString("AddServerErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server.
        /// </summary>
        public static string AddServerLabel {
            get {
                return ResourceManager.GetString("AddServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string CreditsApisLabel {
            get {
                return ResourceManager.GetString("CreditsApisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Mechanism:.
        /// </summary>
        public static string CreditsQueryLabel {
            get {
                return ResourceManager.GetString("CreditsQueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources:.
        /// </summary>
        public static string CreditsResourceLabel {
            get {
                return ResourceManager.GetString("CreditsResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsViewTitle {
            get {
                return ResourceManager.GetString("CreditsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want the project to continue receiving updates you can make a donation here:.
        /// </summary>
        public static string DonateLabel {
            get {
                return ResourceManager.GetString("DonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string DonateName {
            get {
                return ResourceManager.GetString("DonateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesViewTitle {
            get {
                return ResourceManager.GetString("FavoritesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP RCON.
        /// </summary>
        public static string HamburgerHeaderTitle {
            get {
                return ResourceManager.GetString("HamburgerHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string IpLabel {
            get {
                return ResourceManager.GetString("IpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate IP Address.
        /// </summary>
        public static string IpNotLocateError {
            get {
                return ResourceManager.GetString("IpNotLocateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect server.
        /// </summary>
        public static string RconAuthenticationConnectButon {
            get {
                return ResourceManager.GetString("RconAuthenticationConnectButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RCON password..
        /// </summary>
        public static string RconAuthenticationErrorAlert {
            get {
                return ResourceManager.GetString("RconAuthenticationErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON Authentication.
        /// </summary>
        public static string RconAuthenticationViewTitle {
            get {
                return ResourceManager.GetString("RconAuthenticationViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON Password:.
        /// </summary>
        public static string RconPasswordLabel {
            get {
                return ResourceManager.GetString("RconPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string RconSendButtonValue {
            get {
                return ResourceManager.GetString("RconSendButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connection to the server....
        /// </summary>
        public static string RconSuccessfulConnectionMessage {
            get {
                return ResourceManager.GetString("RconSuccessfulConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON Commands.
        /// </summary>
        public static string RconViewTitle {
            get {
                return ResourceManager.GetString("RconViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SACNR servers:.
        /// </summary>
        public static string SacnrTotalServers {
            get {
                return ResourceManager.GetString("SacnrTotalServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string ServersLabel {
            get {
                return ResourceManager.GetString("ServersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ToolBarAdd {
            get {
                return ResourceManager.GetString("ToolBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go down.
        /// </summary>
        public static string ToolBarGoDown {
            get {
                return ResourceManager.GetString("ToolBarGoDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up.
        /// </summary>
        public static string ToolBarGoUp {
            get {
                return ResourceManager.GetString("ToolBarGoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ToolBarRefresh {
            get {
                return ResourceManager.GetString("ToolBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) logged in from SA-MP RCON {2} using {3} {4} OS and {5} {6} device..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
