//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampRcon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampRcon.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to connect to the server failed..
        /// </summary>
        public static string AddServerErrorValue {
            get {
                return ResourceManager.GetString("AddServerErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server.
        /// </summary>
        public static string AddServerLabel {
            get {
                return ResourceManager.GetString("AddServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API:.
        /// </summary>
        public static string CreditsApisLabel {
            get {
                return ResourceManager.GetString("CreditsApisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code:.
        /// </summary>
        public static string CreditsOpenCodeLabel {
            get {
                return ResourceManager.GetString("CreditsOpenCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string CreditsOpenCodeSite {
            get {
                return ResourceManager.GetString("CreditsOpenCodeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Mechanism:.
        /// </summary>
        public static string CreditsQueryLabel {
            get {
                return ResourceManager.GetString("CreditsQueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsViewTitle {
            get {
                return ResourceManager.GetString("CreditsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate:.
        /// </summary>
        public static string DonateLabel {
            get {
                return ResourceManager.GetString("DonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string DonateName {
            get {
                return ResourceManager.GetString("DonateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemode.
        /// </summary>
        public static string ExpanderGamemode {
            get {
                return ResourceManager.GetString("ExpanderGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string ExpanderHostname {
            get {
                return ResourceManager.GetString("ExpanderHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ExpanderLanguage {
            get {
                return ResourceManager.GetString("ExpanderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string ExpanderMap {
            get {
                return ResourceManager.GetString("ExpanderMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ExpanderTime {
            get {
                return ResourceManager.GetString("ExpanderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ExpanderVersion {
            get {
                return ResourceManager.GetString("ExpanderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string ExpanderWebURL {
            get {
                return ResourceManager.GetString("ExpanderWebURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesViewTitle {
            get {
                return ResourceManager.GetString("FavoritesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-MP RCON.
        /// </summary>
        public static string HamburgerHeaderTitle {
            get {
                return ResourceManager.GetString("HamburgerHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        public static string IpLabel {
            get {
                return ResourceManager.GetString("IpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate IP Address.
        /// </summary>
        public static string IpNotLocateError {
            get {
                return ResourceManager.GetString("IpNotLocateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PlayerIDLabel {
            get {
                return ResourceManager.GetString("PlayerIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayerLabel {
            get {
                return ResourceManager.GetString("PlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlayerNameLabel {
            get {
                return ResourceManager.GetString("PlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string PlayerPingLabel {
            get {
                return ResourceManager.GetString("PlayerPingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string PlayerScoreLabel {
            get {
                return ResourceManager.GetString("PlayerScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON commands.
        /// </summary>
        public static string RconHomeCommandTitle {
            get {
                return ResourceManager.GetString("RconHomeCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string RconHomeViewTitle {
            get {
                return ResourceManager.GetString("RconHomeViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect server.
        /// </summary>
        public static string RconLoginConnectButon {
            get {
                return ResourceManager.GetString("RconLoginConnectButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RCON password..
        /// </summary>
        public static string RconLoginErrorAlert {
            get {
                return ResourceManager.GetString("RconLoginErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string RconLoginViewTitle {
            get {
                return ResourceManager.GetString("RconLoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON Password:.
        /// </summary>
        public static string RconPasswordLabel {
            get {
                return ResourceManager.GetString("RconPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string RconSendButtonValue {
            get {
                return ResourceManager.GetString("RconSendButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connection to the server....
        /// </summary>
        public static string RconSuccessfulConnectionMessage {
            get {
                return ResourceManager.GetString("RconSuccessfulConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON Commands.
        /// </summary>
        public static string RconViewTitle {
            get {
                return ResourceManager.GetString("RconViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string RememberRconPasswordLabel {
            get {
                return ResourceManager.GetString("RememberRconPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SACNR:.
        /// </summary>
        public static string SacnrTotalServers {
            get {
                return ResourceManager.GetString("SacnrTotalServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string ServersLabel {
            get {
                return ResourceManager.GetString("ServersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SwipeDelete {
            get {
                return ResourceManager.GetString("SwipeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON.
        /// </summary>
        public static string SwipeRcon {
            get {
                return ResourceManager.GetString("SwipeRcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SwipeSave {
            get {
                return ResourceManager.GetString("SwipeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ToolBarAdd {
            get {
                return ResourceManager.GetString("ToolBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) logged in from SA-MP RCON {2} using {3} {4} OS and {5} {6} device..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
